/* ===================================================================
   Ask view (default in askstat; ?view=editor gives the full editor)
   — question → code → answer. English-first UI (Hans 2026-07-29).
   Pure functions first; DOM wiring below.
   =================================================================== */
(function askViewModule() {

  var ASK_ROUTES = ['beregning', 'data', 'oppslag', 'språk'];

  // Tolerant uthenting av ruter-JSON: modellen skal svare med rent JSON, men
  // vi godtar tekst/kodeblokker rundt. Alt ugyldig → rute 'data' (= dagens
  // data-svar-oppførsel, spec §Feilhåndtering).
  function parseAskRoute(text) {
    var fallback = { rute: 'data', tolkning: '', begrunnelse: '', svar: '' };
    if (!text) return fallback;
    var start = text.indexOf('{');
    var end = text.lastIndexOf('}');
    if (start < 0 || end <= start) return fallback;
    var obj;
    try { obj = JSON.parse(text.slice(start, end + 1)); } catch (_) { return fallback; }
    var rute = (obj && typeof obj.rute === 'string') ? obj.rute.toLowerCase().trim() : '';
    return {
      rute: ASK_ROUTES.indexOf(rute) >= 0 ? rute : 'data',
      tolkning: (obj && typeof obj.tolkning === 'string') ? obj.tolkning : '',
      begrunnelse: (obj && typeof obj.begrunnelse === 'string') ? obj.begrunnelse : '',
      svar: (obj && typeof obj.svar === 'string') ? obj.svar : '',
    };
  }

  // Proveniens-blokk øverst i det genererte scriptet (spec §4): spørsmål,
  // operasjonell tolkning og rute som kommentarer i modusens kommentarsyntaks.
  // For python/r slås kommando-echo av per script (#options.show_commands
  // vinner over appens innstilling — se settings-hinten i index.html).
  var COMMENT_PREFIX = { python: '#', r: '#', duckdb: '--' };
  function buildAskProvenance(meta, mode) {
    var p = COMMENT_PREFIX[mode] || '#';
    var one = function (s) { return String(s || '').replace(/\s*\n\s*/g, ' ').trim(); };
    var lines = [
      p + ' ══ ask ══ generated by askstat',
      p + ' Question: ' + one(meta.question),
      p + ' Interpretation: ' + one(meta.tolkning),
      p + ' Route: ' + one(meta.rute),
    ];
    if (mode === 'python' || mode === 'r') lines.push('#options.show_commands=False');
    return lines.join('\n') + '\n\n';
  }

  // tolk-ask kan flagge semantisk ubrukelig output med en UNUSABLE_OUTPUT:-
  // markørlinje (F1, evallogg 2026-07-29). Skiller markøren fra visningsteksten.
  function parseTolkAnswer(text) {
    var m = /^\s*UNUSABLE_OUTPUT:\s*(.+)$/m.exec(text || '');
    if (!m) return { unusable: false, reason: '', clean: text || '' };
    var clean = (text || '').replace(/^\s*UNUSABLE_OUTPUT:.*$/m, '').trim();
    return { unusable: true, reason: m[1].trim(), clean: clean };
  }

  /* ── DOM wiring (browser only; bails in the node test stub) ─────── */
  function sseAccumulate(resp, onText, signal) {
    // Minimal SSE-leser for tolk-/ruter-endepunktene ({type:'text'|'error'}).
    return new Promise(function (resolve, reject) {
      var reader = resp.body.getReader();
      var decoder = new TextDecoder();
      var buffer = '', accumulated = '';
      function pump() {
        reader.read().then(function (r) {
          if (signal && signal.aborted) { try { reader.cancel(); } catch (_) {} return reject(Object.assign(new Error('Stopped'), { name: 'AbortError' })); }
          if (r.done) return resolve(accumulated);
          buffer += decoder.decode(r.value, { stream: true });
          var nl;
          while ((nl = buffer.indexOf('\n\n')) >= 0) {
            var event = buffer.slice(0, nl);
            buffer = buffer.slice(nl + 2);
            var dataLine = event.split('\n').find(function (l) { return l.indexOf('data:') === 0; });
            if (!dataLine) continue;
            var obj;
            try { obj = JSON.parse(dataLine.slice(5).trim()); } catch (_) { continue; }
            if (obj.type === 'text') { accumulated += obj.text; if (onText) onText(accumulated); }
            else if (obj.type === 'error') { try { reader.cancel(); } catch (_) {} return reject(new Error(obj.message || 'Unknown server error')); }
          }
          pump();
        }, reject);
      }
      pump();
    });
  }

  function switchToEditor() {
    document.documentElement.classList.remove('ask-view');
    var view = document.getElementById('askView');
    if (view) view.hidden = true;
    var url = new URL(location.href);
    url.searchParams.set('view', 'editor');
    history.replaceState(null, '', url.toString());
    window.dispatchEvent(new Event('resize'));   // la editor/plott re-layoute
  }
  function switchToAsk() {
    document.documentElement.classList.add('ask-view');
    var view = document.getElementById('askView');
    if (view) view.hidden = false;
    var url = new URL(location.href);
    url.searchParams.delete('view');
    history.replaceState(null, '', url.toString());
    var input = document.getElementById('askInput');
    if (input) input.focus();
  }

  // Rask vei tilbake til ask fra editor-visningen: liten knapp i toppmenyen
  // (toppmenyen er skjult i ask-visningen, så knappen synes kun i editor).
  function injectTopbarSwitch() {
    var topbar = document.querySelector('header.topbar');
    if (!topbar || document.getElementById('topbarAskSwitch')) return;
    var btn = document.createElement('button');
    btn.type = 'button';
    btn.id = 'topbarAskSwitch';
    btn.className = 'mode-dropdown-btn topbar-ask-switch';
    btn.textContent = '⇄ Ask';
    btn.title = 'Back to the ask view';
    btn.addEventListener('click', switchToAsk);
    topbar.insertBefore(btn, document.getElementById('aiToggleBtn') || null);
  }

  function initAskView() {
    if (!document.querySelector) return;   // node-test-stubben
    injectTopbarSwitch();
    var view = document.getElementById('askView');
    if (!view) return;
    if (document.documentElement.classList.contains('ask-view')) view.hidden = false;

    var md = window.markdownit ? window.markdownit({ breaks: true, linkify: true }) : null;
    var input = document.getElementById('askInput');
    var sendBtn = document.getElementById('askSendBtn');
    var abortBtn = document.getElementById('askAbortBtn');
    var statusBox = document.getElementById('askStatus');
    var answerCard = document.getElementById('askAnswerCard');
    var answerBox = document.getElementById('askAnswer');
    var detailsEl = document.getElementById('askDetails');
    var processBox = document.getElementById('askProcess');
    var running = false;
    var lastAnswerMd = '';

    // Kortere agentiske løp som standard (Hans 2026-07-29 etter
    // «Error in input stream» på hop 7 i deep-modus). Kan endres i
    // AI-innstillingene (Dybde).
    try { if (!localStorage.getItem('md_ai_depth')) localStorage.setItem('md_ai_depth', 'fast'); } catch (e) {}

    // Ask krever en data-svar-kompatibel modus (fence-språk + MODE-prompt).
    // Bare identifier m/typeof-guard, ikke window.-oppslag (let/const-globaler).
    function currentAskMode() {
      return (typeof activeEditorMode !== 'undefined' && activeEditorMode) ? activeEditorMode : 'python';
    }
    if (['python', 'r', 'duckdb'].indexOf(currentAskMode()) < 0 &&
        typeof switchEditorMode === 'function') {
      switchEditorMode('python');
    }

    document.getElementById('askSettingsBtn').addEventListener('click', function () {
      if (window.mdOpenAiSettings) window.mdOpenAiSettings();
    });
    // Hamburger med eksempelspørsmål: klikk fyller feltet (sender ikke — brukeren
    // ser spørsmålet og trykker Ask selv).
    var menuBtn = document.getElementById('askMenuBtn');
    var menu = document.getElementById('askMenu');
    if (menuBtn && menu) {
      menuBtn.addEventListener('click', function (e) { e.stopPropagation(); menu.hidden = !menu.hidden; });
      document.addEventListener('click', function (e) { if (!menu.hidden && !menu.contains(e.target) && e.target !== menuBtn) menu.hidden = true; });
      menu.addEventListener('click', function (e) {
        var b = e.target.closest('button[data-q]');
        if (!b) return;
        input.value = b.dataset.q;
        menu.hidden = true;
        input.focus();
      });
    }
    document.getElementById('askSwitchCode').addEventListener('click', switchToEditor);
    document.getElementById('askOpenEditorBtn').addEventListener('click', switchToEditor);
    document.getElementById('askCopyBtn').addEventListener('click', function () {
      var text = lastAnswerMd || (answerBox ? answerBox.innerText : '');
      if (!text) return;
      navigator.clipboard.writeText(text).catch(function () {});
    });
    document.getElementById('askNewBtn').addEventListener('click', function () {
      answerCard.hidden = true;
      statusBox.innerHTML = '';
      answerBox.innerHTML = '';
      processBox.innerHTML = '';
      detailsEl.hidden = true;
      detailsEl.open = false;
      lastAnswerMd = '';
      input.value = '';
      input.focus();
    });

    function renderMd(node, text) {
      if (md) { try { node.innerHTML = md.render(text || ''); return; } catch (_) {} }
      node.textContent = text || '';
    }
    function progressLine(text) {
      var d = document.createElement('div');
      d.className = 'ai-progress-line';
      d.textContent = '⏳ ' + text;
      statusBox.appendChild(d);
    }
    // Prosess-sporet (hop-progresjon, reparasjonsrunder) vises live i
    // svar-kortet mens det jobbes, og flyttes til «Details» når svaret er
    // klart — så svaret står rett under spørsmålet, ChatGPT-stil.
    function archiveStatus() {
      while (statusBox.firstChild) processBox.appendChild(statusBox.firstChild);
      if (processBox.childNodes.length) detailsEl.hidden = false;
    }
    function showAnswer(markdown, badgeText, badgeWarn) {
      archiveStatus();
      answerCard.hidden = false;
      lastAnswerMd = markdown || '';
      renderMd(answerBox, markdown);
      if (badgeText) {
        var b = document.createElement('div');
        b.className = 'ask-badge' + (badgeWarn ? ' ask-badge-warn' : '');
        b.textContent = badgeText;
        answerBox.insertBefore(b, answerBox.firstChild);
      }
      // Kildelisten fra runWebAnswer flyttes fra prosess-sporet inn i svaret.
      var src = processBox.querySelector('.ai-sources');
      if (src) answerBox.appendChild(src);
    }
    // S2-porten er PÅ KUN ved eksplisitt opt-in (localStorage.md_ask_confirm='1')
    // — ask auto-kjører som standard (Hans 2026-07-29). Injeksjonsrisikoen fra
    // webs søk-genererte script bæres da av brukerens eget nøkkellager.
    function askConfirm() {
      return new Promise(function (resolve) {
        var wrap = document.createElement('div');
        wrap.className = 'ask-confirm';
        var q = document.createElement('span');
        q.textContent = 'Run the generated code? ';
        var yes = document.createElement('button');
        yes.type = 'button'; yes.className = 'ai-response-insert-btn'; yes.textContent = 'Run';
        var no = document.createElement('button');
        no.type = 'button'; no.className = 'ai-codeblock-btn'; no.textContent = 'Cancel';
        wrap.appendChild(q); wrap.appendChild(yes); wrap.appendChild(no);
        statusBox.appendChild(wrap);
        function settle(v) { wrap.remove(); resolve(v); }
        yes.addEventListener('click', function () { settle(true); });
        no.addEventListener('click', function () { settle(false); });
      });
    }
    function confirmChoice() {
      var wantConfirm = false;
      try { wantConfirm = localStorage.getItem('md_ask_confirm') === '1'; } catch (e) {}
      return wantConfirm ? askConfirm : function () { return Promise.resolve(true); };
    }

    async function runAskFlow() {
      var question = input.value.trim();
      if (!question || running) return;
      if (!window.mdAiHasKey || !window.mdAiHasKey()) {
        showAnswer('Ask needs your own API key (stored only in this browser; usage is billed to your own account).', 'API key required', true);
        if (window.mdOpenAiSettings) window.mdOpenAiSettings();
        return;
      }
      running = true;
      sendBtn.disabled = true;
      abortBtn.style.display = '';
      answerCard.hidden = false;   // svaret bygges rett under spørsmålet
      statusBox.innerHTML = '';
      answerBox.innerHTML = '';
      processBox.innerHTML = '';
      detailsEl.hidden = true;
      detailsEl.open = false;
      lastAnswerMd = '';
      var ctrl = new AbortController();
      var onAbort = function () { ctrl.abort(); };
      abortBtn.addEventListener('click', onAbort);
      var uiLang = (window.M2PY_LANG === 'en') ? 'en' : 'no';
      try {
        // 1) Ruter
        progressLine('Interpreting the question …');
        var route = { rute: 'data', tolkning: '', begrunnelse: '', svar: '' };
        try {
          var resp = await fetch('/api/ask-ruter', {
            method: 'POST',
            headers: window.mdAiAuthHeaders(),
            signal: ctrl.signal,
            body: JSON.stringify({ question: question, ui_lang: uiLang, provider: window.mdAiProviderConfig() || undefined }),
          });
          if (resp.ok && resp.body) route = parseAskRoute(await sseAccumulate(resp, null, ctrl.signal));
        } catch (e) { if (e && e.name === 'AbortError') throw e; /* ruterfeil → data-ruten */ }
        progressLine('Route: ' + route.rute + '. Interpretation: ' + (route.tolkning || '—'));

        // 2) Språk-ruten: direkte svar med merking, ingen kode.
        if (route.rute === 'språk') {
          showAnswer(route.svar || 'This question could not be formalized, and the router gave no direct answer.',
            '⚠ Not verified with code or data — plain model answer', true);
          return;
        }

        // 3) Data-svar-løkka (beregning/data/oppslag). Instrukser legges
        //    KLIENT-SIDE i spørsmålsteksten — data-svar-promptene røres ikke.
        var instr;
        if (route.rute === 'beregning') {
          instr = '[Instruction: Pure computation — no external data sources needed. Write one complete script that computes the answer, with comments explaining your choices.]';
        } else if (route.rute === 'oppslag') {
          // F2 (evallogg 2026-07-29): trivielle fakta ble besvart fra hukommelsen
          // uten kilde — krev reelt søk + kilde-URL i svaret.
          instr = '[Instruction: Lookup question — verify the answer with the web search tool and cite at least one authoritative source URL in the answer, even for well-known facts. Never answer purely from memory. Write code only if a computation is genuinely needed.]';
        } else {
          instr = '[Instruction: Comment your choices in the code — why this source/table, this scope, this computation.]';
        }
        var fullQuestion = question +
          (route.tolkning ? '\n\nOperational interpretation (from the router): ' + route.tolkning : '') +
          '\n\n' + instr;
        var prefix = buildAskProvenance({ question: question, tolkning: route.tolkning, rute: route.rute },
          currentAskMode());
        // Output-panelet må være SYNLIG før kjøringen starter — plotly i et
        // display:none-element får null-bredde (spec-ens verifiseringspunkt).
        document.documentElement.classList.add('ask-has-run');

        // Kjør → tolk. Flagger tolk-ask outputen som ubrukelig
        // (UNUSABLE_OUTPUT), gis ÉN semantisk reparasjonsrunde (F1) før det
        // ærlige svaret vises.
        var semanticTries = 0;
        var initialRepair = null;
        while (true) {
          var res = await window.mdAskRun(fullQuestion, {
            processNode: statusBox, signal: ctrl.signal, scriptPrefix: prefix,
            confirm: confirmChoice(), initialRepair: initialRepair,
          });

          if (res.error === 'avbrutt') { progressLine('Stopped.'); archiveStatus(); return; }
          if (!res.ok && res.error === null) {
            // Prosa-svar uten kode (typisk oppslag/web eller ærlig «fant ikke»).
            showAnswer(res.markdown, '⚠ Source-based answer (web search) — not verified with code', true);
            return;
          }
          if (!res.ok) {
            showAnswer('Could not compute this (3 repair rounds failed). Last error:' +
              '\n\n```\n' + String(res.error).slice(0, 800) + '\n```\n\n' +
              'The code is in the code view — use “View code” to inspect and adjust, then try asking again.',
              '⚠ Computation failed', true);
            return;
          }

          // 4) Kjøringen lyktes → tolk-ask komponerer svaret fra output.
          progressLine('Summarizing the result …');
          var outEl = document.getElementById('outputArea');
          var outText = (outEl ? (outEl.innerText || '') : '').trim().slice(0, 30000);
          var si = document.getElementById('scriptInput');
          var script = ((si && si.value) || '').slice(0, 30000);
          var tolkResp = await fetch('/api/tolk-ask', {
            method: 'POST',
            headers: window.mdAiAuthHeaders(),
            signal: ctrl.signal,
            body: JSON.stringify({
              question: question,
              interpretation: route.tolkning,
              script: script,
              output: outText,
              ui_lang: uiLang,
              provider: window.mdAiProviderConfig() || undefined,
            }),
          });
          if (!tolkResp.ok || !tolkResp.body) throw new Error('HTTP ' + tolkResp.status + ' ' + (await tolkResp.text()));
          var finalMd = await sseAccumulate(tolkResp, function (acc) { renderMd(answerBox, parseTolkAnswer(acc).clean); }, ctrl.signal);
          var parsed = parseTolkAnswer(finalMd);
          if (parsed.unusable && semanticTries < 1) {
            semanticTries++;
            progressLine('The output did not answer the question — refining the data query …');
            answerBox.innerHTML = '';
            initialRepair = { script: script,
              error: 'SEMANTIC ERROR — the script ran without errors, but its OUTPUT does not answer the question: ' +
                parsed.reason + ' Fix the data selection/filtering so the OUTPUT actually answers the question.' };
            continue;
          }
          if (parsed.unusable) {
            showAnswer(parsed.clean, '⚠ The computed output did not answer the question', true);
          } else {
            showAnswer(parsed.clean, null, false);
          }
          return;
        }
      } catch (e) {
        if (e && e.name === 'AbortError') { progressLine('Stopped.'); archiveStatus(); }
        else showAnswer('✗ ' + ((e && e.message) ? e.message : String(e)) +
          '\n\nThis is usually a transient stream error — try asking again.', 'Error', true);
      } finally {
        abortBtn.removeEventListener('click', onAbort);
        abortBtn.style.display = 'none';
        sendBtn.disabled = false;
        running = false;
      }
    }

    sendBtn.addEventListener('click', runAskFlow);
    input.addEventListener('keydown', function (e) {
      if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); runAskFlow(); }
    });
    if (document.documentElement.classList.contains('ask-view')) input.focus();
  }

  if (typeof document !== 'undefined' && document.getElementById) {
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', initAskView);
    else initAskView();
  }

  // Node-testbar seam (samme mønster som js/ai-chat.js nederst).
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
      parseAskRoute: parseAskRoute,
      buildAskProvenance: buildAskProvenance,
      parseTolkAnswer: parseTolkAnswer,
    };
  }
})();
