/* ===================================================================
   Ask view (default in askstat; ?view=editor gives the full editor)
   — question → code → answer. English-first UI (Hans 2026-07-29).
   Pure functions first; DOM wiring below.
   =================================================================== */
(function askViewModule() {

  var ASK_ROUTES = ['beregning', 'data', 'oppslag', 'språk', 'utforsk'];

  // Tolerant uthenting av ruter-JSON: modellen skal svare med rent JSON, men
  // vi godtar tekst/kodeblokker rundt. Alt ugyldig → rute 'data' (= dagens
  // data-rute-oppførsel i /api/svar, spec §Feilhåndtering).
  function parseAskRoute(text) {
    var fallback = { rute: 'data', tolkning: '', begrunnelse: '', svar: '' };
    if (!text) return fallback;
    var start = text.indexOf('{');
    var end = text.lastIndexOf('}');
    if (start < 0 || end <= start) return fallback;
    var obj;
    try { obj = JSON.parse(text.slice(start, end + 1)); } catch (_) { return fallback; }
    var rute = (obj && typeof obj.rute === 'string') ? obj.rute.toLowerCase().trim() : '';
    return {
      rute: ASK_ROUTES.indexOf(rute) >= 0 ? rute : 'data',
      tolkning: (obj && typeof obj.tolkning === 'string') ? obj.tolkning : '',
      begrunnelse: (obj && typeof obj.begrunnelse === 'string') ? obj.begrunnelse : '',
      svar: (obj && typeof obj.svar === 'string') ? obj.svar : '',
    };
  }

  // Proveniens-blokk øverst i det genererte scriptet (spec §4): spørsmål,
  // operasjonell tolkning og rute som kommentarer i modusens kommentarsyntaks.
  // For python/r slås kommando-echo av per script (#options.show_commands
  // vinner over appens innstilling — se settings-hinten i index.html).
  var COMMENT_PREFIX = { python: '#', r: '#', duckdb: '--' };
  function buildAskProvenance(meta, mode) {
    var p = COMMENT_PREFIX[mode] || '#';
    var one = function (s) { return String(s || '').replace(/\s*\n\s*/g, ' ').trim(); };
    var lines = [
      p + ' ══ ask ══ generated by askstat',
      p + ' Question: ' + one(meta.question),
      p + ' Interpretation: ' + one(meta.tolkning),
      p + ' Route: ' + one(meta.rute),
    ];
    if (mode === 'python' || mode === 'r') lines.push('#options.show_commands=False');
    return lines.join('\n') + '\n\n';
  }

  // Trestegs-badge (spec 2026-08-04-lokke-niva): siste kjøring bestemmer
  // suksessveien, men en feilet POLERING etter en vellykket kjøring skal
  // ikke stemple svaret rødt (M-Q12-klassen) — mild note i stedet.
  function badgeFor(runHistory) {
    var h = runHistory || [];
    if (!h.length || h[h.length - 1]) return 'ok';
    return h.indexOf(true) >= 0 ? 'feilet-etter-suksess' : 'feilet';
  }

  // Fase 1 konto-runden (spec 2026-08-05): map runAskFlow-utfall → historikk-
  // innslag. Ren funksjon — DOM-fangsten i runAskFlow kaller denne; id/ts
  // settes av AskHistory.save. badgeText/badgeWarn lagres VERBATIM slik de
  // ble vist (tapsfri gjenoppretting; badge-enumen er til fase 2-semantikk).
  function buildHistoryEntry(ctx) {
    return {
      question: ctx.question,
      route: ctx.route || 'data',
      tolkning: ctx.tolkning || '',
      markdown: ctx.markdown || '',
      script: ctx.script || null,
      sources: ctx.sources || [],
      badge: ctx.badge,
      badgeText: ctx.badgeText || null,
      badgeWarn: !!ctx.badgeWarn,
      depth: ctx.depth,
      mode: ctx.mode,
      profileId: ctx.profile ? ctx.profile.id : null,
      profileName: ctx.profile ? ctx.profile.name : null,
    };
  }

  /* ── Output-referanser (spec 2026-07-31-ask-svar-referanser): svaret
     peker på levende output-noder. Ren halvdel her (node-testet);
     DOM-resolveren lenger ned. ─────────────────────────────────────── */
  var ASK_REF_LINE_RE = /^\{\{(fig|table|map|widget|html|controls):([1-9]\d*)\}\}$/;
  // kind (elementtype fra klassifisereren) → referanseklasse
  var KIND_TO_CLASS = {
    plotly: 'fig', png: 'fig', vegalite: 'fig',
    table: 'table', tabulator: 'table',
    map: 'map', widget: 'widget', html: 'html', controls: 'controls',
  };
  var REF_CLASSES = { fig: 1, table: 1, map: 1, widget: 1, html: 1, controls: 1 };

  // assignRefs(items): items er dokumentrekkefølgen av output-elementer —
  // {kind: 'plotly'} for et levende element, {anchor: 'fig:1'} for et
  // hjemreise-anker etter en utflyttet node. Ankre OPPTAR nummeret sitt
  // (utflyttede noder beholder referansen på tvers av delvise
  // re-rendringer) uten selv å bli med i resultatet.
  function assignRefs(items) {
    var counts = {};
    var out = [];
    (items || []).forEach(function (it, i) {
      if (it && it.anchor) {
        var parts = String(it.anchor).split(':');
        var n = parseInt(parts[1], 10);
        if (REF_CLASSES[parts[0]] && n > 0) {
          counts[parts[0]] = Math.max(counts[parts[0]] || 0, n);
        }
        return;
      }
      var cls = it && KIND_TO_CLASS[it.kind];
      if (!cls) return;
      counts[cls] = (counts[cls] || 0) + 1;
      out.push({ ref: cls + ':' + counts[cls], kind: it.kind, idx: i });
    });
    return out;
  }

  // OUTPUTS-linjen i run_code-resultatet (les i sammenheng med
  // svar-prompt.ts sin RUN-blokk — de forteller samme historie).
  function formatOutputsManifest(refs) {
    if (!refs || !refs.length) return '';
    return 'OUTPUTS: ' + refs.map(function (r) {
      return r.kind === r.ref.split(':')[0] ? r.ref : r.ref + ' (' + r.kind + ')';
    }).join(', ');
  }

  // stripRefs: plassholder-alene-linjer → «[fig 1]» (utklippstavle +
  // feilede kjøringer der ingen output finnes å peke på).
  function stripRefs(markdown) {
    return String(markdown == null ? '' : markdown).split('\n').map(function (line) {
      var m = ASK_REF_LINE_RE.exec(line.trim());
      return m ? '[' + m[1] + ' ' + m[2] + ']' : line;
    }).join('\n');
  }

  // planRefResolution: hva skjer med hver plassholder — første forekomst
  // av en referanse vinner (noden kan bare bo ett sted), ukjente droppes.
  function planRefResolution(availableRefs, placeholderRefs) {
    var avail = {};
    (availableRefs || []).forEach(function (r) { avail[r] = true; });
    var used = {};
    return (placeholderRefs || []).map(function (ref) {
      if (!avail[ref]) return { ref: ref, action: 'drop-unknown' };
      if (used[ref]) return { ref: ref, action: 'drop-dup' };
      used[ref] = true;
      return { ref: ref, action: 'resolve' };
    });
  }

  // DOM-klassifisereren: wrapper-selektorene fra buildOutputNodes/mdRender*
  // (index.html). Rekkefølgen er også kind-prioritet ved treff.
  var ASK_OUT_SELECTORS = [
    ['.plotly-container', 'plotly'],
    ['img.output-matplotlib-img', 'png'],
    ['.vegalite-container', 'vegalite'],
    ['.tabulator-embed', 'tabulator'],
    ['.output-table-wrap', 'table'],
    ['.leafletmap-container', 'map'],
    ['.ipw-view', 'widget'],
    ['.output-html-embed', 'html'],
    ['.param-form', 'controls'],
    ['.ui-controls', 'controls'],
  ];
  var ASK_OUT_SELECTOR_ALL = ASK_OUT_SELECTORS.map(function (s) { return s[0]; }).join(', ');
  var ASK_SCAN_SELECTOR = ASK_OUT_SELECTOR_ALL + ', .ask-out-anchor';

  // mdClassifyAskOutput(container) → [{ref, kind, el}] i dokumentrekkefølge.
  // Nøstede treff (element inni et annet treff) hoppes over — wrapperen er
  // referansen. Ankre telles med i nummereringen (se assignRefs) men
  // returneres ikke.
  function classifyAskOutput(container) {
    if (!container || !container.querySelectorAll) return [];
    var els = Array.prototype.slice.call(container.querySelectorAll(ASK_SCAN_SELECTOR));
    els = els.filter(function (el) {
      return !(el.parentElement && el.parentElement.closest &&
               el.parentElement.closest(ASK_OUT_SELECTOR_ALL));
    });
    var items = els.map(function (el) {
      if (el.classList && el.classList.contains('ask-out-anchor')) {
        return { anchor: (el.dataset && el.dataset.ref) || '' };
      }
      for (var i = 0; i < ASK_OUT_SELECTORS.length; i++) {
        if (el.matches && el.matches(ASK_OUT_SELECTORS[i][0])) {
          return { kind: ASK_OUT_SELECTORS[i][1] };
        }
      }
      return {};
    });
    return assignRefs(items).map(function (r) {
      return { ref: r.ref, kind: r.kind, el: els[r.idx] };
    });
  }
  if (typeof window !== 'undefined') {
    window.mdClassifyAskOutput = classifyAskOutput;
    window.mdAskManifest = formatOutputsManifest;
    // AI-panelet (js/ai-chat.js) deler /api/svar men har ingen resolver —
    // stripRefs er dets eneste vei bort fra rå {{fig:1}}-tekst.
    window.mdAskStripRefs = stripRefs;
  }

  /* Levende output i svarkortet (spec §Output + 2026-07-31-referanser):
     #outputArea-noden FLYTTES (ikke klones) etter vellykket kjøring —
     til #askLiveOutput (synlig, fallback uten plassholdere) eller inn i
     «Full output»-folden (#askFullOutputHost) når svaret refererer
     enkeltnoder. Flyttes tilbake ved nytt spørsmål/kodevisning. */
  var outputHome = null;
  function resizePlotlyIn(root) {
    if (!window.Plotly || !window.Plotly.Plots || !root.querySelectorAll) return;
    root.querySelectorAll('.js-plotly-plot').forEach(function (p) {
      try { window.Plotly.Plots.resize(p); } catch (_) { /* plotly borte */ }
    });
  }
  function mountOutputInto(hostId) {
    var out = document.getElementById('outputArea');
    var host = document.getElementById(hostId);
    if (!out || !host || out.dataset.askMounted === '1') return;
    outputHome = { parent: out.parentNode, next: out.nextSibling };
    out.dataset.askMounted = '1';
    var details = host.closest && host.closest('details');
    if (details) details.hidden = false; else host.hidden = false;
    host.appendChild(out);
    window.dispatchEvent(new Event('resize'));
    resizePlotlyIn(out);
  }
  function mountLiveOutput() { mountOutputInto('askLiveOutput'); }
  function mountFullOutput() { mountOutputInto('askFullOutputHost'); }
  function unmountLiveOutput() {
    stopReResolveObserver();
    returnSlotNodesHome();
    var out = document.getElementById('outputArea');
    var live = document.getElementById('askLiveOutput');
    var details = document.getElementById('askFullOutput');
    if (live) live.hidden = true;
    if (details) { details.hidden = true; details.open = false; }
    if (!out || out.dataset.askMounted !== '1' || !outputHome) return;
    delete out.dataset.askMounted;
    outputHome.parent.insertBefore(out, outputHome.next);
    outputHome = null;
    window.dispatchEvent(new Event('resize'));
  }

  /* Re-resolve (spec §5): renderOutput/celle-re-kjøringer bygger NYE noder
     i #outputArea — slots re-fylles med ferske noder med samme referanse.
     Samme debounce-mønster som observeOutputAreaForCopyButtons
     (index.html): {childList, subtree}, 150 ms. disconnect/observe-paret
     rundt egne mutasjoner hindrer selv-trigging (observer-løkke). */
  var _reResolveObserver = null;
  var _reResolveTimer = null;
  function startReResolveObserver() {
    var out = document.getElementById('outputArea');
    if (!out || typeof MutationObserver === 'undefined' || _reResolveObserver) return;
    _reResolveObserver = new MutationObserver(function () {
      if (_reResolveTimer) clearTimeout(_reResolveTimer);
      _reResolveTimer = setTimeout(reResolveSlots, 150);
    });
    _reResolveObserver.observe(out, { childList: true, subtree: true });
  }
  function stopReResolveObserver() {
    if (_reResolveTimer) { clearTimeout(_reResolveTimer); _reResolveTimer = null; }
    if (_reResolveObserver) { _reResolveObserver.disconnect(); _reResolveObserver = null; }
  }
  function reResolveSlots() {
    var out = document.getElementById('outputArea');
    var slots = askAnswerSlots();
    var obs = _reResolveObserver;
    if (!out || !slots.length) return;
    if (obs) obs.disconnect();
    try {
      var byRef = {};
      classifyAskOutput(out).forEach(function (r) { byRef[r.ref] = r.el; });
      slots.forEach(function (slot) {
        var ref = slot.dataset.ref;
        var fresh = byRef[ref];
        if (fresh) {
          // Ny node med denne referansen finnes i outputen → bytt.
          // purgePlots her: slotten er UTENFOR #outputArea, så
          // renderOutput sin egen purge nådde aldri den gamle noden.
          if (window.purgePlots) window.purgePlots(slot);
          slot.innerHTML = '';
          moveIntoSlot(slot, fresh);
          return;
        }
        // Ingen fersk node: lever ankeret? → noden i slotten lever videre
        // (re-rendringen traff en annen celle). Anker borte → referansen
        // finnes ikke lenger (f.eks. færre figurer med ny param-verdi) →
        // slotten står tom (spec §5 pkt 4).
        var anchor = out.querySelector('.ask-out-anchor[data-ref="' + ref + '"]');
        if (!anchor) {
          if (window.purgePlots) window.purgePlots(slot);
          slot.innerHTML = '';
        }
      });
    } finally {
      if (obs && _reResolveObserver === obs) {
        obs.observe(out, { childList: true, subtree: true });
      }
    }
  }

  // Flytt en levende output-node inn i en slot; etterlat et anker
  // (hjemreisebillett + nummer-plassholder for classifyAskOutput).
  function moveIntoSlot(slot, el) {
    var anchor = document.createElement('span');
    anchor.className = 'ask-out-anchor';
    anchor.dataset.ref = slot.dataset.ref;
    el.parentNode.insertBefore(anchor, el);
    slot.appendChild(el);
    resizePlotlyIn(slot);
    // Re-resolvet markdown-embed (§5) må få matten sin tilbake — KaTeX
    // rendret den opprinnelige noden, ikke denne ferske erstatningen.
    // typeof-vaktet: kun kjør om KaTeX alt er lastet (respekter lazy-last).
    if (typeof renderMathInElement === 'function' && slot.querySelectorAll) {
      Array.prototype.slice.call(slot.querySelectorAll('.output-markdown'))
        .forEach(function (el2) {
          try { renderMathInElement(el2, KATEX_OPTS); } catch (_) {}
        });
    }
  }

  function askAnswerSlots() {
    var box = document.getElementById('askAnswer');
    return box ? Array.prototype.slice.call(box.querySelectorAll('.ask-out-slot')) : [];
  }

  // resolveAnswerRefs: bytt {{fig:1}}-avsnitt i #askAnswer mot slots med
  // levende noder fra #outputArea. Returnerer antall resolvede slots —
  // 0 → kalleren faller tilbake til dagens mountLiveOutput-oppførsel.
  function resolveAnswerRefs() {
    var box = document.getElementById('askAnswer');
    var out = document.getElementById('outputArea');
    if (!box || !out) return 0;
    var byRef = {};
    classifyAskOutput(out).forEach(function (r) { byRef[r.ref] = r.el; });
    var candidates = Array.prototype.slice.call(box.querySelectorAll('p'))
      .map(function (p) {
        var m = ASK_REF_LINE_RE.exec((p.textContent || '').trim());
        return m ? { p: p, ref: m[1] + ':' + m[2] } : null;
      }).filter(Boolean);
    var plan = planRefResolution(Object.keys(byRef),
      candidates.map(function (c) { return c.ref; }));
    var resolved = 0;
    plan.forEach(function (step, i) {
      var p = candidates[i].p;
      if (step.action !== 'resolve') { p.remove(); return; }
      var slot = document.createElement('div');
      slot.className = 'ask-out-slot';
      slot.dataset.ref = step.ref;
      p.replaceWith(slot);
      moveIntoSlot(slot, byRef[step.ref]);
      resolved++;
    });
    return resolved;
  }

  // sweepUnresolvedRefs: siste sikkerhetsnett mot rå plassholdertekst.
  // markdown-it kjører med breaks:true — en plassholder UTEN blanke linjer
  // rundt havner inni et større <p>, og resolveAnswerRefs sitt
  // hele-avsnitt-treff (ASK_REF_LINE_RE mot p.textContent) fyrer aldri.
  // Går derfor gjennom tekstnodene under #askAnswer og bytter inline —
  // slotter (allerede resolvet, kan inneholde brukerdata) holdes utenfor.
  var ASK_REF_INLINE_RE = /\{\{(fig|table|map|widget|html|controls):([1-9]\d*)\}\}/g;
  function sweepUnresolvedRefs() {
    var box = document.getElementById('askAnswer');
    if (!box || typeof document.createTreeWalker !== 'function') return;
    var walker = document.createTreeWalker(box, NodeFilter.SHOW_TEXT, {
      acceptNode: function (node) {
        var parent = node.parentElement;
        if (!parent) return NodeFilter.FILTER_REJECT;
        if (parent.closest('.ask-out-slot')) return NodeFilter.FILTER_REJECT;
        if (parent.closest('script, style')) return NodeFilter.FILTER_REJECT;
        return NodeFilter.FILTER_ACCEPT;
      },
    });
    var node;
    while ((node = walker.nextNode())) {
      if (node.nodeValue.indexOf('{{') >= 0) {
        node.nodeValue = node.nodeValue.replace(ASK_REF_INLINE_RE, '[$1 $2]');
      }
    }
  }

  // Hjemreise (spec §4): slot-noder tilbake til ankrene sine FØR svaret
  // tømmes eller #outputArea flyttes hjem — slik forblir purgePlots +
  // renderOutput sin innerHTML='' den ENESTE oppryddingsveien, ingen
  // plotly-lekkasje fra noder som bor utenfor #outputArea.
  function returnSlotNodesHome() {
    var out = document.getElementById('outputArea');
    askAnswerSlots().forEach(function (slot) {
      var node = slot.firstElementChild;
      if (node && out) {
        var anchor = out.querySelector('.ask-out-anchor[data-ref="' + slot.dataset.ref + '"]');
        if (anchor) anchor.replaceWith(node);
        else out.appendChild(node);   // anker re-rendret bort → bakerst
      }
      slot.remove();
    });
    if (out) {
      Array.prototype.slice.call(out.querySelectorAll('.ask-out-anchor'))
        .forEach(function (a) { a.remove(); });
    }
  }

  /* ── Matte-maskering (målt 2026-08-01): markdown-it behandler _ og *
     INNE i $$…$$ som emphasis (`}_{`-underscorene i en \underbrace-ligning
     ble spist som kursiv-par og <em> splittet tekstnoden), så KaTeX
     auto-render fant aldri delimiterne og rå, lemlestet LaTeX ble stående.
     Segmentene maskeres med private-use-plassholdere FØR md.render og
     gjeninnsettes HTML-escapet etterpå — da står uskadd LaTeX i ÉN
     tekstnode når auto-render leter. Samme delimitere som KATEX_OPTS. ── */
  var MATH_SEG_RE = /\$\$[\s\S]+?\$\$|\\\[[\s\S]+?\\\]|\\\([\s\S]+?\\\)|\$[^$\n]+\$/g;
  function maskMathSegments(text) {
    var segs = [];
    var masked = String(text || '').replace(MATH_SEG_RE, function (m) {
      segs.push(m);
      return '\uE000' + (segs.length - 1) + '\uE001';
    });
    return { masked: masked, segs: segs };
  }
  function restoreMathSegments(html, segs) {
    return String(html || '').replace(/\uE000(\d+)\uE001/g, function (whole, i) {
      var seg = segs[Number(i)];
      if (seg === undefined) return whole;
      return seg.replace(/[&<>"']/g, function (c) {
        return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
      });
    });
  }

  /* KaTeX (spec §6): lazy — lastes KUN når svaret ser ut til å inneholde
     matte. Idempotent per fane (promise-cache, samme mønster som
     _loadImportScript i index.html). CDN-feil → rå LaTeX blir stående,
     aldri kast. */
  var KATEX_BASE = 'https://cdn.jsdelivr.net/npm/katex@0.16.21/dist/';
  // ignoredClasses: auto-render sin egen tekstnode-vandring skal ALDRI gå inn
  // i adopterte levende output-noder (Plotly/vegalite/leaflet/tabulator m.fl.
  // muterer sine egne subtrær kontinuerlig — KaTeX som går der er både
  // bortkastet og et krasj-risiko-punkt). Samme klasseliste som
  // ASK_OUT_SELECTORS over, minus punktum-prefikset.
  var KATEX_OPTS = {
    delimiters: [
      { left: '$$', right: '$$', display: true },
      { left: '\\[', right: '\\]', display: true },
      { left: '\\(', right: '\\)', display: false },
      { left: '$', right: '$', display: false },
    ],
    throwOnError: false,
    ignoredClasses: ['plotly-container', 'vegalite-container', 'leafletmap-container',
      'tabulator-embed', 'ipw-view', 'output-html-embed', 'param-form', 'ui-controls'],
  };
  var _katexP = null;
  function _addTag(make) {
    return new Promise(function (resolve, reject) {
      var el = make();
      el.onload = resolve;
      el.onerror = function () { reject(new Error('KaTeX-lasting feilet')); };
      document.head.appendChild(el);
    });
  }
  function ensureKatex() {
    if (_katexP) return _katexP;
    _katexP = _addTag(function () {
      var l = document.createElement('link');
      l.rel = 'stylesheet'; l.href = KATEX_BASE + 'katex.min.css'; return l;
    }).then(function () {
      return _addTag(function () {
        var s = document.createElement('script');
        s.src = KATEX_BASE + 'katex.min.js'; return s;
      });
    }).then(function () {
      return _addTag(function () {
        var s = document.createElement('script');
        s.src = KATEX_BASE + 'contrib/auto-render.min.js'; return s;
      });
    }).catch(function (e) { _katexP = null; throw e; });
    return _katexP;
  }
  var MATH_HINT_RE = /\$|\\\(|\\\[/;
  function maybeRenderMath(markdown) {
    if (!MATH_HINT_RE.test(String(markdown || ''))) return;
    ensureKatex().then(function () {
      if (typeof renderMathInElement !== 'function') return;
      var box = document.getElementById('askAnswer');
      if (box) { try { renderMathInElement(box, KATEX_OPTS); } catch (_) {} }
      // Best effort (spec §6): matte i kjøringens egne markdown-embeds.
      Array.prototype.slice.call(
        document.querySelectorAll('#outputArea .output-markdown, .ask-out-slot .output-markdown')
      ).forEach(function (el) {
        try { renderMathInElement(el, KATEX_OPTS); } catch (_) {}
      });
    }).catch(function () { /* CDN nede → rå LaTeX står igjen */ });
  }

  /* ── DOM wiring (browser only; bails in the node test stub) ─────── */
  function sseAccumulate(resp, onText, signal) {
    // Minimal SSE-leser for tolk-/ruter-endepunktene ({type:'text'|'error'}).
    return new Promise(function (resolve, reject) {
      var reader = resp.body.getReader();
      var decoder = new TextDecoder();
      var buffer = '', accumulated = '';
      function pump() {
        reader.read().then(function (r) {
          if (signal && signal.aborted) { try { reader.cancel(); } catch (_) {} return reject(Object.assign(new Error('Stopped'), { name: 'AbortError' })); }
          if (r.done) return resolve(accumulated);
          buffer += decoder.decode(r.value, { stream: true });
          var nl;
          while ((nl = buffer.indexOf('\n\n')) >= 0) {
            var event = buffer.slice(0, nl);
            buffer = buffer.slice(nl + 2);
            var dataLine = event.split('\n').find(function (l) { return l.indexOf('data:') === 0; });
            if (!dataLine) continue;
            var obj;
            try { obj = JSON.parse(dataLine.slice(5).trim()); } catch (_) { continue; }
            if (obj.type === 'text') { accumulated += obj.text; if (onText) onText(accumulated); }
            else if (obj.type === 'error') { try { reader.cancel(); } catch (_) {} return reject(new Error(obj.message || 'Unknown server error')); }
          }
          pump();
        }, reject);
      }
      pump();
    });
  }

  function switchToEditor() {
    unmountLiveOutput();
    document.documentElement.classList.remove('ask-view');
    var view = document.getElementById('askView');
    if (view) view.hidden = true;
    var url = new URL(location.href);
    url.searchParams.set('view', 'editor');
    history.replaceState(null, '', url.toString());
    window.dispatchEvent(new Event('resize'));   // la editor/plott re-layoute
  }
  function switchToAsk() {
    document.documentElement.classList.add('ask-view');
    var view = document.getElementById('askView');
    if (view) view.hidden = false;
    var url = new URL(location.href);
    url.searchParams.delete('view');
    history.replaceState(null, '', url.toString());
    var input = document.getElementById('askInput');
    if (input) input.focus();
  }

  // Vei tilbake til ask fra editor-visningen: blå, sentrert knapp i topp-
  // menyen (toppmenyen er skjult i ask-visningen, så knappen synes kun i
  // editor). Absolutt sentrert via .topbar-ask-switch — DOM-plasseringen
  // i topbaren er derfor likegyldig.
  function injectTopbarSwitch() {
    var topbar = document.querySelector('header.topbar');
    if (!topbar || document.getElementById('topbarAskSwitch')) return;
    var btn = document.createElement('button');
    btn.type = 'button';
    btn.id = 'topbarAskSwitch';
    btn.className = 'topbar-ask-switch';
    btn.textContent = 'Ask mode';
    btn.title = 'Back to the ask view';
    btn.addEventListener('click', switchToAsk);
    topbar.appendChild(btn);
  }

  function initAskView() {
    if (!document.querySelector) return;   // node-test-stubben
    injectTopbarSwitch();
    var view = document.getElementById('askView');
    if (!view) return;
    if (document.documentElement.classList.contains('ask-view')) view.hidden = false;

    var md = window.markdownit ? window.markdownit({ breaks: true, linkify: true }) : null;
    // Delt markdown-rendrer for profil-/pakke-forhåndsvisning (spec 2026-08-05
    // §2: markdown i profiler er offisielt). Ren md.render — ingen mattemaskering.
    window.mdAskMarkdown = function (s) { return md ? md.render(String(s || '')) : ''; };
    var input = document.getElementById('askInput');
    var sendBtn = document.getElementById('askSendBtn');
    var abortBtn = document.getElementById('askAbortBtn');
    var statusBox = document.getElementById('askStatus');
    var answerCard = document.getElementById('askAnswerCard');
    var answerBox = document.getElementById('askAnswer');
    var detailsEl = document.getElementById('askDetails');
    var processBox = document.getElementById('askProcess');
    var running = false;
    var lastAnswerMd = '';

    // Ask krever en svar-kompatibel modus (fence-språk + MODE-prompt).
    // Bare identifier m/typeof-guard, ikke window.-oppslag (let/const-globaler).
    function currentAskMode() {
      return (typeof activeEditorMode !== 'undefined' && activeEditorMode) ? activeEditorMode : 'python';
    }
    if (['python', 'r', 'duckdb'].indexOf(currentAskMode()) < 0 &&
        typeof switchEditorMode === 'function') {
      switchEditorMode('python');
    }

    document.getElementById('askSettingsBtn').addEventListener('click', function () {
      if (window.mdOpenAiSettings) window.mdOpenAiSettings();
    });
    // Hamburger med eksempelspørsmål: klikk fyller feltet (sender ikke — brukeren
    // ser spørsmålet og trykker Ask selv).
    var menuBtn = document.getElementById('askMenuBtn');
    var menu = document.getElementById('askMenu');
    if (menuBtn && menu) {
      menuBtn.addEventListener('click', function (e) { e.stopPropagation(); menu.hidden = !menu.hidden; });
      document.addEventListener('click', function (e) { if (!menu.hidden && !menu.contains(e.target) && e.target !== menuBtn) menu.hidden = true; });
      menu.addEventListener('click', function (e) {
        var b = e.target.closest('button[data-q]');
        if (!b) return;
        input.value = b.dataset.q;
        menu.hidden = true;
        input.focus();
      });
    }

    // Deep-only (spec 2026-08-05-sprak-pakker-deling §1): dybdevelgeren er
    // fjernet; feltet beholdes i payload/historikk/telemetri som konstant.
    function askDepth() { return 'deep'; }

    // Why AskStat?-modalen (copy-runden 2026-08-05): to innganger — sidebar-
    // knappen og lenkelinja under taglinen.
    var aboutBackdrop = document.getElementById('askAboutBackdrop');
    function openAbout(e) {
      if (e) e.preventDefault();
      if (aboutBackdrop) aboutBackdrop.classList.add('open');
    }
    var aboutBtn = document.getElementById('askAboutBtn');
    var aboutLink = document.getElementById('askAboutLink');
    var aboutClose = document.getElementById('askAboutCloseBtn');
    if (aboutBtn) aboutBtn.addEventListener('click', openAbout);
    if (aboutLink) aboutLink.addEventListener('click', openAbout);
    if (aboutClose) aboutClose.addEventListener('click', function () { aboutBackdrop.classList.remove('open'); });
    if (aboutBackdrop) aboutBackdrop.addEventListener('click', function (e) {
      if (e.target === aboutBackdrop) aboutBackdrop.classList.remove('open');
    });

    // Kollapsbar sidebar (layout-runden 2026-08-05): full ↔ tynn ikonskinne,
    // valget huskes per nettleser (md_ask_sidebar).
    var sidebarEl = document.getElementById('askSidebar');
    var sideToggle = document.getElementById('askSidebarToggle');
    var LS_SIDEBAR = 'md_ask_sidebar';
    function applySidebarMode() {
      var thin = false;
      try { thin = localStorage.getItem(LS_SIDEBAR) === 'thin'; } catch (e) {}
      if (sidebarEl) sidebarEl.classList.toggle('thin', thin);
      if (sideToggle) {
        sideToggle.title = thin ? 'Expand sidebar' : 'Collapse sidebar';
        sideToggle.setAttribute('aria-label', sideToggle.title);
      }
    }
    if (sideToggle && sidebarEl) {
      sideToggle.addEventListener('click', function () {
        var thin = sidebarEl.classList.contains('thin');
        try { localStorage.setItem(LS_SIDEBAR, thin ? 'full' : 'thin'); } catch (e) {}
        applySidebarMode();
      });
    }
    applySidebarMode();

    // Tekstfeltet vokser med innholdet (maks-høyde i CSS), Claude-stil.
    input.addEventListener('input', function () {
      input.style.height = 'auto';
      input.style.height = Math.min(input.scrollHeight, 220) + 'px';
    });

    // Historikk-sidebar (konto-runden fase 1). renderHistoryList kalles også
    // fra saveHistory i runAskFlow (function declaration → hoistet).
    var histWrap = document.getElementById('askHistoryWrap');
    var histList = document.getElementById('askHistoryList');
    function renderHistoryList() {
      if (!histWrap || !histList || !window.AskHistory) return;
      var items = window.AskHistory.list();
      histWrap.hidden = !items.length;
      histList.innerHTML = '';
      items.forEach(function (e) {
        var row = document.createElement('div');
        row.className = 'ask-hist-item';
        var open = document.createElement('button');
        open.type = 'button';
        open.className = 'ask-hist-open';
        open.title = e.question + ' (' + String(e.ts).slice(0, 10) + ')';
        open.textContent = e.question.length > 60 ? e.question.slice(0, 57) + '…' : e.question;
        open.addEventListener('click', function () { restoreEntry(e.id); });
        var del = document.createElement('button');
        del.type = 'button';
        del.className = 'ask-hist-del';
        del.textContent = '×';
        del.title = 'Delete';
        del.addEventListener('click', function (ev) {
          ev.stopPropagation();
          window.AskHistory.remove(e.id);
          renderHistoryList();
        });
        row.appendChild(open);
        row.appendChild(del);
        histList.appendChild(row);
      });
    }
    document.getElementById('askHistoryClear').addEventListener('click', function () {
      if (window.AskHistory) window.AskHistory.clear();
      renderHistoryList();
    });
    // Gjenoppretting fra historikk (spec §Fase 1a): lagret markdown vises
    // med [fig N]-klammer; «Run code again» re-kjører det lagrede scriptet
    // LOKALT (pyodide — null LLM-kostnad) og resolver {{fig:N}} på nytt.
    var rerunBtn = document.getElementById('askRerunBtn');
    var restoredEntry = null;
    function restoreEntry(id) {
      if (running) return;
      var e = window.AskHistory && window.AskHistory.get(id);
      if (!e) return;
      restoredEntry = e;
      stopReResolveObserver();
      unmountLiveOutput();
      fullOutBtn.hidden = true;
      statusBox.innerHTML = '';
      processBox.innerHTML = '';
      detailsEl.open = false;
      input.value = e.question;
      showAnswer(stripRefs(e.markdown), e.badgeText, e.badgeWarn);
      // Inline-plassholdere (uten blanke linjer rundt) fanges ikke av
      // stripRefs — samme sikkerhetsnett som ok-grenen i runAskFlow.
      sweepUnresolvedRefs();
      renderSources(e.sources);
      maybeRenderMath(e.markdown);
      var note = document.createElement('div');
      note.className = 'ai-progress-line';
      note.textContent = '↩ Restored from history (asked ' + String(e.ts).slice(0, 10) + ')';
      processBox.appendChild(note);
      detailsEl.hidden = false;
      rerunBtn.hidden = !e.script;
    }
    async function rerunRestored() {
      var e = restoredEntry;
      if (!e || !e.script || running || !window.mdAskExecuteScript) return;
      running = true;
      sendBtn.disabled = true;
      rerunBtn.disabled = true;
      abortBtn.style.display = '';
      var ctrl = new AbortController();
      var onAbort = function () { ctrl.abort(); };
      abortBtn.addEventListener('click', onAbort);
      progressLine('Running the code …');
      try {
        var r = await window.mdAskExecuteScript(e.script, ctrl.signal);
        archiveStatus();
        if (r.ok) {
          // Samme montering som ok-grenen i runAskFlow: rå markdown m/
          // {{fig:N}} → levende slots (ref-nummerering er deterministisk
          // DOM-orden i classifyAskOutput).
          renderMd(answerBox, e.markdown);
          if (e.badgeText) {
            var b = document.createElement('div');
            b.className = 'ask-badge' + (e.badgeWarn ? ' ask-badge-warn' : '');
            b.textContent = e.badgeText;
            answerBox.insertBefore(b, answerBox.firstChild);
          }
          lastAnswerMd = e.markdown;
          renderSources(e.sources);
          fullOutBtn.hidden = false;
          if (resolveAnswerRefs() > 0) {
            mountFullOutput();
            startReResolveObserver();
          } else {
            mountLiveOutput();
          }
          sweepUnresolvedRefs();
          maybeRenderMath(e.markdown);
        } else {
          var d = document.createElement('div');
          d.className = 'ai-progress-line';
          d.textContent = '✗ Run failed — the restored text above is unchanged. ' +
            String((r && r.result) || '').slice(0, 300);
          processBox.appendChild(d);
          detailsEl.hidden = false;
          detailsEl.open = true;
        }
      } catch (err) { /* abort → stille; teksten står */ }
      finally {
        abortBtn.removeEventListener('click', onAbort);
        abortBtn.style.display = 'none';
        sendBtn.disabled = false;
        rerunBtn.disabled = false;
        running = false;
      }
    }
    rerunBtn.addEventListener('click', rerunRestored);
    renderHistoryList();

    document.getElementById('askSwitchCode').addEventListener('click', switchToEditor);
    document.getElementById('askOpenEditorBtn').addEventListener('click', switchToEditor);
    document.getElementById('askCopyBtn').addEventListener('click', function () {
      var text = lastAnswerMd ? stripRefs(lastAnswerMd) : (answerBox ? answerBox.innerText : '');
      if (!text) return;
      navigator.clipboard.writeText(text).catch(function () {});
    });
    // «Full output»: vis alt kjøringen produserte uten å forlate ask-visningen.
    // Output-noden kan alt bo i folden (referanse-svar), i den synlige
    // fallback-verten, eller fortsatt i editoren (feilede kjøringer) — da
    // monteres den i folden først. Knappen vises kun når kode faktisk kjørte.
    var fullOutBtn = document.getElementById('askFullOutputBtn');
    fullOutBtn.addEventListener('click', function () {
      var out = document.getElementById('outputArea');
      var details = document.getElementById('askFullOutput');
      if (!out) return;
      if (out.dataset.askMounted !== '1') mountFullOutput();
      var inFold = details && details.contains(out);
      if (inFold) { details.open = true; resizePlotlyIn(out); }
      var target = inFold ? details : out;
      if (target.scrollIntoView) target.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    });
    document.getElementById('askNewBtn').addEventListener('click', function () {
      unmountLiveOutput();
      fullOutBtn.hidden = true;
      answerCard.hidden = true;
      statusBox.innerHTML = '';
      answerBox.innerHTML = '';
      processBox.innerHTML = '';
      detailsEl.hidden = true;
      detailsEl.open = false;
      lastAnswerMd = '';
      rerunBtn.hidden = true;
      restoredEntry = null;
      input.value = '';
      input.focus();
    });

    function renderMd(node, text) {
      if (md) {
        try {
          var mm = maskMathSegments(text || '');
          node.innerHTML = restoreMathSegments(md.render(mm.masked), mm.segs);
          return;
        } catch (_) {}
      }
      node.textContent = text || '';
    }
    function esc(s) {
      return String(s).replace(/[&<>"']/g, function (c) {
        return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
      });
    }
    function renderSources(list) {
      if (!list || !list.length) return;
      var div = document.createElement('div');
      div.className = 'ai-sources';
      div.innerHTML = '<b>Sources:</b> ' + list.map(function (s) {
        return (s.ok ? '✅ ' : '⚠️ ') +
          '<a href="' + esc(s.url) + '" target="_blank" rel="noopener">' +
          esc(s.url.replace(/^https?:\/\//, '').slice(0, 60)) + '</a>' +
          (s.viaProxy ? ' (via proxy)' : '');
      }).join(' · ');
      answerBox.appendChild(div);
    }
    function progressLine(text) {
      var d = document.createElement('div');
      d.className = 'ai-progress-line';
      d.textContent = '⏳ ' + text;
      statusBox.appendChild(d);
    }
    // Prosess-sporet (hop-progresjon, reparasjonsrunder) vises live i
    // svar-kortet mens det jobbes, og flyttes til «Details» når svaret er
    // klart — så svaret står rett under spørsmålet, ChatGPT-stil.
    function archiveStatus() {
      while (statusBox.firstChild) processBox.appendChild(statusBox.firstChild);
      if (processBox.childNodes.length) detailsEl.hidden = false;
    }
    function showAnswer(markdown, badgeText, badgeWarn) {
      archiveStatus();
      answerCard.hidden = false;
      lastAnswerMd = markdown || '';
      renderMd(answerBox, markdown);
      if (badgeText) {
        var b = document.createElement('div');
        b.className = 'ask-badge' + (badgeWarn ? ' ask-badge-warn' : '');
        b.textContent = badgeText;
        answerBox.insertBefore(b, answerBox.firstChild);
      }
    }
    // S2-porten er PÅ KUN ved eksplisitt opt-in (localStorage.md_ask_confirm='1')
    // — ask auto-kjører som standard (Hans 2026-07-29). Injeksjonsrisikoen fra
    // webs søk-genererte script bæres da av brukerens eget nøkkellager.
    function askConfirm() {
      return new Promise(function (resolve) {
        var wrap = document.createElement('div');
        wrap.className = 'ask-confirm';
        var q = document.createElement('span');
        q.textContent = 'Run the generated code? ';
        var yes = document.createElement('button');
        yes.type = 'button'; yes.className = 'ai-response-insert-btn'; yes.textContent = 'Run';
        var no = document.createElement('button');
        no.type = 'button'; no.className = 'ai-codeblock-btn'; no.textContent = 'Cancel';
        wrap.appendChild(q); wrap.appendChild(yes); wrap.appendChild(no);
        statusBox.appendChild(wrap);
        function settle(v) { wrap.remove(); resolve(v); }
        yes.addEventListener('click', function () { settle(true); });
        no.addEventListener('click', function () { settle(false); });
      });
    }
    function confirmChoice() {
      var wantConfirm = false;
      try { wantConfirm = localStorage.getItem('md_ask_confirm') === '1'; } catch (e) {}
      return wantConfirm ? askConfirm : function () { return Promise.resolve(true); };
    }

    async function runAskFlow() {
      var question = input.value.trim();
      if (!question || running) return;
      if (!window.mdAiHasKey || !window.mdAiHasKey()) {
        showAnswer('Ask needs your own API key (stored only in this browser; usage is billed to your own account).', 'API key required', true);
        if (window.mdOpenAiSettings) window.mdOpenAiSettings();
        return;
      }
      running = true;
      sendBtn.disabled = true;
      abortBtn.style.display = '';
      unmountLiveOutput();
      fullOutBtn.hidden = true;
      answerCard.hidden = false;
      statusBox.innerHTML = '';
      answerBox.innerHTML = '';
      processBox.innerHTML = '';
      detailsEl.hidden = true;
      detailsEl.open = false;
      lastAnswerMd = '';
      rerunBtn.hidden = true;
      restoredEntry = null;
      var ctrl = new AbortController();
      var onAbort = function () { ctrl.abort(); };
      abortBtn.addEventListener('click', onAbort);
      var uiLang = (window.M2PY_LANG === 'en') ? 'en' : 'no';
      var feilRuns = [];
      var runHistory = [];
      var lastSources = [];
      var route = { rute: 'data', tolkning: '', begrunnelse: '', svar: '' };
      // Konto-runden fase 1: historikk-fangst. Profilen leses ved flytstart
      // (proveniens); siste VELLYKKEDE script lagres for «Run code again».
      var lastOkScript = null;
      var activeProfile = (window.Profiles && window.Profiles.active && window.Profiles.active()) || null;
      function saveHistory(markdown, badge, badgeText, badgeWarn, script, sources) {
        if (!window.AskHistory) return;
        try {
          window.AskHistory.save(buildHistoryEntry({
            question: question, route: route.rute, tolkning: route.tolkning,
            markdown: markdown, script: script, sources: sources,
            badge: badge, badgeText: badgeText, badgeWarn: badgeWarn,
            depth: askDepth(), mode: currentAskMode(), profile: activeProfile,
          }));
          if (typeof renderHistoryList === 'function') renderHistoryList();
        } catch (e) {}
      }
      function sendTelemetri(flowError) {
        if (!window.FeilTelemetri) return;
        if (!feilRuns.length && !flowError) return;
        window.FeilTelemetri.sendFeilrapport({
          version: window.M2PY_VERSION || '',
          ui_lang: uiLang,
          mode: currentAskMode(),
          route: route.rute,
          depth: askDepth(),
          question: question,
          tolkning: route.tolkning,
          runs: feilRuns,
          flow_error: flowError || undefined,
          final_ok: lastRunOk,
          probed_sources: lastSources,
          provider_type: (window.mdAiProviderConfig && window.mdAiProviderConfig() || {}).type || 'anthropic',
        });
      }
      try {
        // 1) Ruter (uendret): rute + operasjonell tolkning.
        progressLine('Interpreting the question …');
        try {
          var resp = await fetch('/api/ask-ruter', {
            method: 'POST',
            headers: window.mdAiAuthHeaders(),
            signal: ctrl.signal,
            body: JSON.stringify({ question: question, ui_lang: uiLang, provider: window.mdAiProviderConfig() || undefined }),
          });
          if (resp.ok && resp.body) route = parseAskRoute(await sseAccumulate(resp, null, ctrl.signal));
        } catch (e) { if (e && e.name === 'AbortError') throw e; /* ruterfeil → data-ruten */ }
        progressLine('Route: ' + route.rute + '. Interpretation: ' + (route.tolkning || '—'));
        // Aktiv profil skal aldri usynlig forme svar (spec §Fase 1b) —
        // linjen arkiveres til Details sammen med resten av prosess-sporet.
        if (activeProfile) progressLine('Profile applied: ' + activeProfile.name);
        // Kildepakke skal heller aldri usynlig forme svar (spec 2026-08-05 §2).
        var packSt = (window.Profiles && window.Profiles.packState) ? window.Profiles.packState() : null;
        if (packSt && packSt.id && window.Packs) {
          progressLine('Pack applied: ' + window.Packs.displayName(packSt.id) + (packSt.auto ? ' (auto)' : ''));
        }

        // 2) Språk-ruten: direkte svar med merking, ingen kode (uendret).
        if (route.rute === 'språk') {
          showAnswer(route.svar || 'This question could not be formalized, and the router gave no direct answer.',
            '⚠ Not verified with code or data — plain model answer', true);
          saveHistory(route.svar || 'This question could not be formalized, and the router gave no direct answer.',
            'ingen-kjøring', '⚠ Not verified with code or data — plain model answer', true, null, []);
          return;
        }

        // 3) Ett agentisk løp: /api/svar med run_code som klientverktøy.
        var fullQuestion = question +
          (route.tolkning ? '\n\nOperational interpretation (from the router): ' + route.tolkning : '');
        var prefix = buildAskProvenance({ question: question, tolkning: route.tolkning, rute: route.rute },
          currentAskMode());
        var confirm = confirmChoice();
        var confirmed = false;
        var lastRunOk = false;
        // Did the run ever reach onRunCode? Distinguishes "code ran and
        // failed" (still warn, even with 0 probed sources) from "no code was
        // ever executed" (e.g. oppslag/språk-style answers via the data
        // path) — the latter must not get a false "code did not run" badge.
        var ranAny = false;
        var res = await window.mdSvarRun({
          question: fullQuestion,
          route: route.rute,
          depth: askDepth(),
          mode: currentAskMode(),
          signal: ctrl.signal,
          handlers: {
            onProgress: function (ev) {
              var last = statusBox.lastElementChild;
              if (ev.replace && last && last.dataset && last.dataset.replace === '1') {
                last.textContent = '⏳ ' + ev.text;
                return;
              }
              var line = document.createElement('div');
              line.className = 'ai-progress-line';
              if (ev.replace) line.dataset.replace = '1';
              line.textContent = '⏳ ' + ev.text;
              statusBox.appendChild(line);
            },
            onDelta: function (full) { renderMd(answerBox, full); },
            onTurnDiscard: function (full) {
              if (!full || !full.trim()) return;
              var d = document.createElement('div');
              d.className = 'ai-progress-line';
              d.textContent = '📝 ' + full.trim().slice(0, 200);
              statusBox.appendChild(d);
            },
            onRunCode: async function (script) {
              ranAny = true;
              if (!confirmed) {
                var ok = await confirm();
                if (!ok) {
                  ctrl.abort();
                  throw Object.assign(new Error('Stopped'), { name: 'AbortError' });
                }
                confirmed = true;
              }
              progressLine('Running the code …');
              var r = await window.mdAskExecuteScript(prefix + script, ctrl.signal);
              lastRunOk = r.ok;
              runHistory.push(r.ok);
              if (r.ok) lastOkScript = prefix + script;
              if (!r.ok) feilRuns.push({ script: prefix + script, error: r.result });
              return r.result;
            },
          },
        });

        lastSources = (res.sources || []).map(function (s) { return s.url; });

        // 4) Sluttsvaret er allerede strømmet inn — arkiver prosess-sporet,
        //    vis kilder, og monter levende output ved vellykket kjøring.
        // Trestegs-badge (spec 2026-08-04-lokke-niva): badgeFor ser på HELE
        // kjøringshistorikken, ikke bare siste kjøring — en feilet
        // POLERING etter en vellykket kjøring skal ikke stemple svaret
        // rødt (M-Q12-klassen). runHistory er alltid ikke-tom her (ranAny
        // gate: onRunCode har kjørt minst én gang), så badgeFor sitt
        // 'ok'-for-tom-liste-tilfelle nås aldri i denne grenen.
        if (ranAny) {
          fullOutBtn.hidden = false;
          switch (badgeFor(runHistory)) {
            case 'ok':
              showAnswer(res.markdown, null, false);
              renderSources(res.sources);
              // Kuratert svar (spec 2026-07-31): plassholdere → levende noder.
              // ≥1 resolvet → resten bak «Full output»-folden; 0 → dagens
              // synlige mount (trygg degradering når modellen ignorerer
              // kontrakten).
              if (resolveAnswerRefs() > 0) {
                mountFullOutput();
                startReResolveObserver();
              } else {
                mountLiveOutput();
              }
              // Sikkerhetsnett (spec §Feilhåndtering): modellen kan sette
              // plassholderen uten blanke linjer rundt → blir stående rå i
              // et <p> resolveAnswerRefs aldri så.
              sweepUnresolvedRefs();
              maybeRenderMath(res.markdown);
              saveHistory(res.markdown, 'ok', null, false, lastOkScript, res.sources || []);
              break;
            case 'feilet-etter-suksess':
              // Siste kjøring (poleringen) feilet, men en tidligere kjøring
              // lyktes — mild, nøytral note (ikke rød): plassholdere har
              // ingen pålitelig output å peke på, strip til klammetekst.
              showAnswer(stripRefs(res.markdown),
                '⚠ Last polish run failed — the numbers come from an earlier successful run', false);
              renderSources(res.sources);
              maybeRenderMath(res.markdown);
              saveHistory(res.markdown, 'feilet-etter-suksess',
                '⚠ Last polish run failed — the numbers come from an earlier successful run', false,
                lastOkScript, res.sources || []);
              break;
            case 'feilet':
            default:
              // Kjøring forsøkt og feilet — plassholdere har ingen pålitelig
              // output å peke på: strip til klammetekst.
              showAnswer(stripRefs(res.markdown),
                '⚠ The code did not run successfully — treat numbers with caution', true);
              renderSources(res.sources);
              maybeRenderMath(res.markdown);
              saveHistory(res.markdown, 'feilet',
                '⚠ The code did not run successfully — treat numbers with caution', true,
                null, res.sources || []);
              break;
          }
        } else {
          showAnswer(stripRefs(res.markdown),
            res.sources && res.sources.length
              ? '⚠ Source-based answer — the code did not run successfully'
              : null,
            true);
          renderSources(res.sources);
          maybeRenderMath(res.markdown);
          saveHistory(res.markdown, 'ingen-kjøring',
            (res.sources && res.sources.length
              ? '⚠ Source-based answer — the code did not run successfully'
              : null),
            true, null, res.sources || []);
        }
        sendTelemetri(null);
      } catch (e) {
        if (e && e.name === 'AbortError') {
          progressLine('Stopped.'); archiveStatus();
          if (feilRuns.length) sendTelemetri(null);
        }
        else {
          sendTelemetri((e && e.message) ? e.message : String(e));
          showAnswer('✗ ' + ((e && e.message) ? e.message : String(e)) +
            '\n\nThis is usually a transient stream error — try asking again.', 'Error', true);
        }
      } finally {
        abortBtn.removeEventListener('click', onAbort);
        abortBtn.style.display = 'none';
        sendBtn.disabled = false;
        running = false;
      }
    }

    sendBtn.addEventListener('click', runAskFlow);
    input.addEventListener('keydown', function (e) {
      if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); runAskFlow(); }
    });
    if (document.documentElement.classList.contains('ask-view')) input.focus();
  }

  if (typeof document !== 'undefined' && document.getElementById) {
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', initAskView);
    else initAskView();
  }

  // Node-testbar seam (samme mønster som js/ai-chat.js nederst).
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
      parseAskRoute: parseAskRoute,
      buildAskProvenance: buildAskProvenance,
      badgeFor: badgeFor,
      buildHistoryEntry: buildHistoryEntry,
      assignRefs: assignRefs,
      formatOutputsManifest: formatOutputsManifest,
      stripRefs: stripRefs,
      planRefResolution: planRefResolution,
      maskMathSegments: maskMathSegments,
      restoreMathSegments: restoreMathSegments,
    };
  }
})();
