/* ===================================================================
   Ask view (default in askstat; ?view=editor gives the full editor)
   — question → code → answer. English-first UI (Hans 2026-07-29).
   Pure functions first; DOM wiring below.
   =================================================================== */
(function askViewModule() {

  var ASK_ROUTES = ['beregning', 'data', 'oppslag', 'språk'];

  // Tolerant uthenting av ruter-JSON: modellen skal svare med rent JSON, men
  // vi godtar tekst/kodeblokker rundt. Alt ugyldig → rute 'data' (= dagens
  // data-rute-oppførsel i /api/svar, spec §Feilhåndtering).
  function parseAskRoute(text) {
    var fallback = { rute: 'data', tolkning: '', begrunnelse: '', svar: '' };
    if (!text) return fallback;
    var start = text.indexOf('{');
    var end = text.lastIndexOf('}');
    if (start < 0 || end <= start) return fallback;
    var obj;
    try { obj = JSON.parse(text.slice(start, end + 1)); } catch (_) { return fallback; }
    var rute = (obj && typeof obj.rute === 'string') ? obj.rute.toLowerCase().trim() : '';
    return {
      rute: ASK_ROUTES.indexOf(rute) >= 0 ? rute : 'data',
      tolkning: (obj && typeof obj.tolkning === 'string') ? obj.tolkning : '',
      begrunnelse: (obj && typeof obj.begrunnelse === 'string') ? obj.begrunnelse : '',
      svar: (obj && typeof obj.svar === 'string') ? obj.svar : '',
    };
  }

  // Proveniens-blokk øverst i det genererte scriptet (spec §4): spørsmål,
  // operasjonell tolkning og rute som kommentarer i modusens kommentarsyntaks.
  // For python/r slås kommando-echo av per script (#options.show_commands
  // vinner over appens innstilling — se settings-hinten i index.html).
  var COMMENT_PREFIX = { python: '#', r: '#', duckdb: '--' };
  function buildAskProvenance(meta, mode) {
    var p = COMMENT_PREFIX[mode] || '#';
    var one = function (s) { return String(s || '').replace(/\s*\n\s*/g, ' ').trim(); };
    var lines = [
      p + ' ══ ask ══ generated by askstat',
      p + ' Question: ' + one(meta.question),
      p + ' Interpretation: ' + one(meta.tolkning),
      p + ' Route: ' + one(meta.rute),
    ];
    if (mode === 'python' || mode === 'r') lines.push('#options.show_commands=False');
    return lines.join('\n') + '\n\n';
  }

  // Dybde for /api/svar: 'standard' er default; velges på split-knappen.
  function coerceAskDepth(v) { return v === 'deep' ? 'deep' : 'standard'; }

  /* Levende output i svarkortet (spec §Output): selve #outputArea-noden
     FLYTTES inn i kortet etter vellykket kjøring (ikke klones) — interaktiv
     plotly og widgets/#@param-re-kjøringer virker der den står. Flyttes
     tilbake ved nytt spørsmål eller bytte til kodevisningen. */
  var outputHome = null;
  function mountLiveOutput() {
    var out = document.getElementById('outputArea');
    var host = document.getElementById('askLiveOutput');
    if (!out || !host || out.dataset.askMounted === '1') return;
    outputHome = { parent: out.parentNode, next: out.nextSibling };
    out.dataset.askMounted = '1';
    host.hidden = false;
    host.appendChild(out);
    window.dispatchEvent(new Event('resize'));
    if (window.Plotly && window.Plotly.Plots) {
      out.querySelectorAll('.js-plotly-plot').forEach(function (p) {
        try { window.Plotly.Plots.resize(p); } catch (_) { /* plotly borte */ }
      });
    }
  }
  function unmountLiveOutput() {
    var out = document.getElementById('outputArea');
    var host = document.getElementById('askLiveOutput');
    if (!out || out.dataset.askMounted !== '1' || !outputHome) return;
    delete out.dataset.askMounted;
    if (host) host.hidden = true;
    outputHome.parent.insertBefore(out, outputHome.next);
    outputHome = null;
    window.dispatchEvent(new Event('resize'));
  }

  /* ── DOM wiring (browser only; bails in the node test stub) ─────── */
  function sseAccumulate(resp, onText, signal) {
    // Minimal SSE-leser for tolk-/ruter-endepunktene ({type:'text'|'error'}).
    return new Promise(function (resolve, reject) {
      var reader = resp.body.getReader();
      var decoder = new TextDecoder();
      var buffer = '', accumulated = '';
      function pump() {
        reader.read().then(function (r) {
          if (signal && signal.aborted) { try { reader.cancel(); } catch (_) {} return reject(Object.assign(new Error('Stopped'), { name: 'AbortError' })); }
          if (r.done) return resolve(accumulated);
          buffer += decoder.decode(r.value, { stream: true });
          var nl;
          while ((nl = buffer.indexOf('\n\n')) >= 0) {
            var event = buffer.slice(0, nl);
            buffer = buffer.slice(nl + 2);
            var dataLine = event.split('\n').find(function (l) { return l.indexOf('data:') === 0; });
            if (!dataLine) continue;
            var obj;
            try { obj = JSON.parse(dataLine.slice(5).trim()); } catch (_) { continue; }
            if (obj.type === 'text') { accumulated += obj.text; if (onText) onText(accumulated); }
            else if (obj.type === 'error') { try { reader.cancel(); } catch (_) {} return reject(new Error(obj.message || 'Unknown server error')); }
          }
          pump();
        }, reject);
      }
      pump();
    });
  }

  function switchToEditor() {
    unmountLiveOutput();
    document.documentElement.classList.remove('ask-view');
    var view = document.getElementById('askView');
    if (view) view.hidden = true;
    var url = new URL(location.href);
    url.searchParams.set('view', 'editor');
    history.replaceState(null, '', url.toString());
    window.dispatchEvent(new Event('resize'));   // la editor/plott re-layoute
  }
  function switchToAsk() {
    document.documentElement.classList.add('ask-view');
    var view = document.getElementById('askView');
    if (view) view.hidden = false;
    var url = new URL(location.href);
    url.searchParams.delete('view');
    history.replaceState(null, '', url.toString());
    var input = document.getElementById('askInput');
    if (input) input.focus();
  }

  // Rask vei tilbake til ask fra editor-visningen: liten knapp i toppmenyen
  // (toppmenyen er skjult i ask-visningen, så knappen synes kun i editor).
  function injectTopbarSwitch() {
    var topbar = document.querySelector('header.topbar');
    if (!topbar || document.getElementById('topbarAskSwitch')) return;
    var btn = document.createElement('button');
    btn.type = 'button';
    btn.id = 'topbarAskSwitch';
    btn.className = 'mode-dropdown-btn topbar-ask-switch';
    btn.textContent = '⇄ Ask';
    btn.title = 'Back to the ask view';
    btn.addEventListener('click', switchToAsk);
    topbar.insertBefore(btn, document.getElementById('aiToggleBtn') || null);
  }

  function initAskView() {
    if (!document.querySelector) return;   // node-test-stubben
    injectTopbarSwitch();
    var view = document.getElementById('askView');
    if (!view) return;
    if (document.documentElement.classList.contains('ask-view')) view.hidden = false;

    var md = window.markdownit ? window.markdownit({ breaks: true, linkify: true }) : null;
    var input = document.getElementById('askInput');
    var sendBtn = document.getElementById('askSendBtn');
    var abortBtn = document.getElementById('askAbortBtn');
    var statusBox = document.getElementById('askStatus');
    var answerCard = document.getElementById('askAnswerCard');
    var answerBox = document.getElementById('askAnswer');
    var detailsEl = document.getElementById('askDetails');
    var processBox = document.getElementById('askProcess');
    var running = false;
    var lastAnswerMd = '';

    // Ask krever en svar-kompatibel modus (fence-språk + MODE-prompt).
    // Bare identifier m/typeof-guard, ikke window.-oppslag (let/const-globaler).
    function currentAskMode() {
      return (typeof activeEditorMode !== 'undefined' && activeEditorMode) ? activeEditorMode : 'python';
    }
    if (['python', 'r', 'duckdb'].indexOf(currentAskMode()) < 0 &&
        typeof switchEditorMode === 'function') {
      switchEditorMode('python');
    }

    document.getElementById('askSettingsBtn').addEventListener('click', function () {
      if (window.mdOpenAiSettings) window.mdOpenAiSettings();
    });
    // Hamburger med eksempelspørsmål: klikk fyller feltet (sender ikke — brukeren
    // ser spørsmålet og trykker Ask selv).
    var menuBtn = document.getElementById('askMenuBtn');
    var menu = document.getElementById('askMenu');
    if (menuBtn && menu) {
      menuBtn.addEventListener('click', function (e) { e.stopPropagation(); menu.hidden = !menu.hidden; });
      document.addEventListener('click', function (e) { if (!menu.hidden && !menu.contains(e.target) && e.target !== menuBtn) menu.hidden = true; });
      menu.addEventListener('click', function (e) {
        var b = e.target.closest('button[data-q]');
        if (!b) return;
        input.value = b.dataset.q;
        menu.hidden = true;
        input.focus();
      });
    }

    var LS_ASK_DEPTH = 'md_ask_depth';
    function askDepth() {
      try { return coerceAskDepth(localStorage.getItem(LS_ASK_DEPTH)); } catch (e) { return 'standard'; }
    }
    var depthBtn = document.getElementById('askDepthBtn');
    var depthMenu = document.getElementById('askDepthMenu');
    function syncDepthUi() {
      var d = askDepth();
      sendBtn.textContent = d === 'deep' ? 'Ask (deep)' : 'Ask';
      depthMenu.querySelectorAll('button[data-depth]').forEach(function (b) {
        b.classList.toggle('active', b.dataset.depth === d);
      });
    }
    depthBtn.addEventListener('click', function (e) { e.stopPropagation(); depthMenu.hidden = !depthMenu.hidden; });
    document.addEventListener('click', function (e) {
      if (!depthMenu.hidden && !depthMenu.contains(e.target) && e.target !== depthBtn) depthMenu.hidden = true;
    });
    depthMenu.addEventListener('click', function (e) {
      var b = e.target.closest('button[data-depth]');
      if (!b) return;
      try { localStorage.setItem(LS_ASK_DEPTH, b.dataset.depth); } catch (_) {}
      depthMenu.hidden = true;
      syncDepthUi();
    });
    syncDepthUi();

    document.getElementById('askSwitchCode').addEventListener('click', switchToEditor);
    document.getElementById('askOpenEditorBtn').addEventListener('click', switchToEditor);
    document.getElementById('askCopyBtn').addEventListener('click', function () {
      var text = lastAnswerMd || (answerBox ? answerBox.innerText : '');
      if (!text) return;
      navigator.clipboard.writeText(text).catch(function () {});
    });
    document.getElementById('askNewBtn').addEventListener('click', function () {
      unmountLiveOutput();
      answerCard.hidden = true;
      statusBox.innerHTML = '';
      answerBox.innerHTML = '';
      processBox.innerHTML = '';
      detailsEl.hidden = true;
      detailsEl.open = false;
      lastAnswerMd = '';
      input.value = '';
      input.focus();
    });

    function renderMd(node, text) {
      if (md) { try { node.innerHTML = md.render(text || ''); return; } catch (_) {} }
      node.textContent = text || '';
    }
    function esc(s) {
      return String(s).replace(/[&<>"']/g, function (c) {
        return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c];
      });
    }
    function renderSources(list) {
      if (!list || !list.length) return;
      var div = document.createElement('div');
      div.className = 'ai-sources';
      div.innerHTML = '<b>Sources:</b> ' + list.map(function (s) {
        return (s.ok ? '✅ ' : '⚠️ ') +
          '<a href="' + esc(s.url) + '" target="_blank" rel="noopener">' +
          esc(s.url.replace(/^https?:\/\//, '').slice(0, 60)) + '</a>' +
          (s.viaProxy ? ' (via proxy)' : '');
      }).join(' · ');
      answerBox.appendChild(div);
    }
    function progressLine(text) {
      var d = document.createElement('div');
      d.className = 'ai-progress-line';
      d.textContent = '⏳ ' + text;
      statusBox.appendChild(d);
    }
    // Prosess-sporet (hop-progresjon, reparasjonsrunder) vises live i
    // svar-kortet mens det jobbes, og flyttes til «Details» når svaret er
    // klart — så svaret står rett under spørsmålet, ChatGPT-stil.
    function archiveStatus() {
      while (statusBox.firstChild) processBox.appendChild(statusBox.firstChild);
      if (processBox.childNodes.length) detailsEl.hidden = false;
    }
    function showAnswer(markdown, badgeText, badgeWarn) {
      archiveStatus();
      answerCard.hidden = false;
      lastAnswerMd = markdown || '';
      renderMd(answerBox, markdown);
      if (badgeText) {
        var b = document.createElement('div');
        b.className = 'ask-badge' + (badgeWarn ? ' ask-badge-warn' : '');
        b.textContent = badgeText;
        answerBox.insertBefore(b, answerBox.firstChild);
      }
    }
    // S2-porten er PÅ KUN ved eksplisitt opt-in (localStorage.md_ask_confirm='1')
    // — ask auto-kjører som standard (Hans 2026-07-29). Injeksjonsrisikoen fra
    // webs søk-genererte script bæres da av brukerens eget nøkkellager.
    function askConfirm() {
      return new Promise(function (resolve) {
        var wrap = document.createElement('div');
        wrap.className = 'ask-confirm';
        var q = document.createElement('span');
        q.textContent = 'Run the generated code? ';
        var yes = document.createElement('button');
        yes.type = 'button'; yes.className = 'ai-response-insert-btn'; yes.textContent = 'Run';
        var no = document.createElement('button');
        no.type = 'button'; no.className = 'ai-codeblock-btn'; no.textContent = 'Cancel';
        wrap.appendChild(q); wrap.appendChild(yes); wrap.appendChild(no);
        statusBox.appendChild(wrap);
        function settle(v) { wrap.remove(); resolve(v); }
        yes.addEventListener('click', function () { settle(true); });
        no.addEventListener('click', function () { settle(false); });
      });
    }
    function confirmChoice() {
      var wantConfirm = false;
      try { wantConfirm = localStorage.getItem('md_ask_confirm') === '1'; } catch (e) {}
      return wantConfirm ? askConfirm : function () { return Promise.resolve(true); };
    }

    async function runAskFlow() {
      var question = input.value.trim();
      if (!question || running) return;
      if (!window.mdAiHasKey || !window.mdAiHasKey()) {
        showAnswer('Ask needs your own API key (stored only in this browser; usage is billed to your own account).', 'API key required', true);
        if (window.mdOpenAiSettings) window.mdOpenAiSettings();
        return;
      }
      running = true;
      sendBtn.disabled = true;
      abortBtn.style.display = '';
      unmountLiveOutput();
      answerCard.hidden = false;
      statusBox.innerHTML = '';
      answerBox.innerHTML = '';
      processBox.innerHTML = '';
      detailsEl.hidden = true;
      detailsEl.open = false;
      lastAnswerMd = '';
      var ctrl = new AbortController();
      var onAbort = function () { ctrl.abort(); };
      abortBtn.addEventListener('click', onAbort);
      var uiLang = (window.M2PY_LANG === 'en') ? 'en' : 'no';
      try {
        // 1) Ruter (uendret): rute + operasjonell tolkning.
        progressLine('Interpreting the question …');
        var route = { rute: 'data', tolkning: '', begrunnelse: '', svar: '' };
        try {
          var resp = await fetch('/api/ask-ruter', {
            method: 'POST',
            headers: window.mdAiAuthHeaders(),
            signal: ctrl.signal,
            body: JSON.stringify({ question: question, ui_lang: uiLang, provider: window.mdAiProviderConfig() || undefined }),
          });
          if (resp.ok && resp.body) route = parseAskRoute(await sseAccumulate(resp, null, ctrl.signal));
        } catch (e) { if (e && e.name === 'AbortError') throw e; /* ruterfeil → data-ruten */ }
        progressLine('Route: ' + route.rute + '. Interpretation: ' + (route.tolkning || '—'));

        // 2) Språk-ruten: direkte svar med merking, ingen kode (uendret).
        if (route.rute === 'språk') {
          showAnswer(route.svar || 'This question could not be formalized, and the router gave no direct answer.',
            '⚠ Not verified with code or data — plain model answer', true);
          return;
        }

        // 3) Ett agentisk løp: /api/svar med run_code som klientverktøy.
        var fullQuestion = question +
          (route.tolkning ? '\n\nOperational interpretation (from the router): ' + route.tolkning : '');
        var prefix = buildAskProvenance({ question: question, tolkning: route.tolkning, rute: route.rute },
          currentAskMode());
        var confirm = confirmChoice();
        var confirmed = false;
        var lastRunOk = false;
        // Did the run ever reach onRunCode? Distinguishes "code ran and
        // failed" (still warn, even with 0 probed sources) from "no code was
        // ever executed" (e.g. oppslag/språk-style answers via the data
        // path) — the latter must not get a false "code did not run" badge.
        var ranAny = false;
        var res = await window.mdSvarRun({
          question: fullQuestion,
          route: route.rute,
          depth: askDepth(),
          mode: currentAskMode(),
          signal: ctrl.signal,
          handlers: {
            onProgress: function (ev) {
              var last = statusBox.lastElementChild;
              if (ev.replace && last && last.dataset && last.dataset.replace === '1') {
                last.textContent = '⏳ ' + ev.text;
                return;
              }
              var line = document.createElement('div');
              line.className = 'ai-progress-line';
              if (ev.replace) line.dataset.replace = '1';
              line.textContent = '⏳ ' + ev.text;
              statusBox.appendChild(line);
            },
            onDelta: function (full) { renderMd(answerBox, full); },
            onTurnDiscard: function (full) {
              if (!full || !full.trim()) return;
              var d = document.createElement('div');
              d.className = 'ai-progress-line';
              d.textContent = '📝 ' + full.trim().slice(0, 200);
              statusBox.appendChild(d);
            },
            onRunCode: async function (script) {
              ranAny = true;
              if (!confirmed) {
                var ok = await confirm();
                if (!ok) {
                  ctrl.abort();
                  throw Object.assign(new Error('Stopped'), { name: 'AbortError' });
                }
                confirmed = true;
              }
              progressLine('Running the code …');
              var r = await window.mdAskExecuteScript(prefix + script, ctrl.signal);
              lastRunOk = r.ok;
              return r.result;
            },
          },
        });

        // 4) Sluttsvaret er allerede strømmet inn — arkiver prosess-sporet,
        //    vis kilder, og monter levende output ved vellykket kjøring.
        if (lastRunOk) {
          showAnswer(res.markdown, null, false);
          renderSources(res.sources);
          mountLiveOutput();
        } else if (ranAny) {
          // Code was actually attempted and did not succeed — warn
          // regardless of how many sources were probed (0 probed sources
          // here means the run failed before/without probing, not that
          // nothing needs a warning).
          showAnswer(res.markdown,
            '⚠ The code did not run successfully — treat numbers with caution', true);
          renderSources(res.sources);
        } else {
          // No code ever ran (e.g. oppslag/språk-style answers via the data
          // path) — only warn if there were probed sources to caveat.
          showAnswer(res.markdown,
            res.sources && res.sources.length
              ? '⚠ Source-based answer — the code did not run successfully'
              : null,
            true);
          renderSources(res.sources);
        }
      } catch (e) {
        if (e && e.name === 'AbortError') { progressLine('Stopped.'); archiveStatus(); }
        else showAnswer('✗ ' + ((e && e.message) ? e.message : String(e)) +
          '\n\nThis is usually a transient stream error — try asking again.', 'Error', true);
      } finally {
        abortBtn.removeEventListener('click', onAbort);
        abortBtn.style.display = 'none';
        sendBtn.disabled = false;
        running = false;
      }
    }

    sendBtn.addEventListener('click', runAskFlow);
    input.addEventListener('keydown', function (e) {
      if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); runAskFlow(); }
    });
    if (document.documentElement.classList.contains('ask-view')) input.focus();
  }

  if (typeof document !== 'undefined' && document.getElementById) {
    if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', initAskView);
    else initAskView();
  }

  // Node-testbar seam (samme mønster som js/ai-chat.js nederst).
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = {
      parseAskRoute: parseAskRoute,
      buildAskProvenance: buildAskProvenance,
      coerceAskDepth: coerceAskDepth,
    };
  }
})();
